Repository PlaceOS/frontend-loader, pull requests merged in 2022-04, with the labels that each got.

#55 fix(loader): remove the creation of the base www model
  src/placeos-frontend-loader/loader.cr
Labels: type: bug

#57 feat(logging): optional log level from ENV var
  src/logging.cr
Labels: product: placeos, priority: high, squad: core, focus: backend, type: enhancement

#58 chore(Dockerfile): bump crystal version
  Dockerfile
  shard.lock
  shard.yml
  src/app.cr
Labels: type: chore

#59 fix(logging): bring inline with other services
  shard.lock
  shard.yml
  src/app.cr
  src/logging.cr
Labels: product: placeos, priority: high, squad: core, focus: backend

#60 feat: add support for generic repositories
  spec/api/repositories_spec.cr
  src/placeos-frontend-loader/api/remote/generic.cr
  src/placeos-frontend-loader/api/remote/github.cr
  src/placeos-frontend-loader/api/remote/gitlab.cr
  src/placeos-frontend-loader/api/remote/remote.cr
  src/placeos-frontend-loader/api/repositories.cr
  src/placeos-frontend-loader/loader.cr
Labels: product: placeos, priority: critical, squad: core, focus: backend, type: enhancement
